### ISSUE TITLE
Homologar nombres de funciones

### ISSUE THREAD

**Issue by mucinoab** [mucinoab/Covid#52]
En idioma, snake case, etc.

**Comment by dianapg8** [comment]
Covid.csv_a_DataFrame*
Covid.contar_renglones
Covid.cargar_csv()*    antes Covid.data_check()
Covid.filtrar
Covid.poblacion_entidad
Covid.poblacion_mexico
Covid.poblacion_municipio
Covid.poblacion_todas_entidades*    antes Covid.poblacion_todos_entidades()
Covid.poblacion_todos_municipios
Covid.seleccionar
Covid.sumar_columna*     antes sumacolumna()
Covid.sumar_fila*     antes sumafila()

**Comment by dianapg8** [comment]
Acordar nombres de estas funciones:
intensidad migratoria
indice de pobreza
mediana de edad + cuartiles de edad;   edad()
natalidad + fecundidad + mortalidad   tasas()*
extension territorial <- +poblacion()
codigos postales    cod_postales()
coord geo + altitud media;     geografia()
