### ISSUE TITLE
clave()

### ISSUE THREAD

**Issue by dianapg8** [mucinoab/Covid#83]

**Comment by mucinoab** [comment]
Se apreciarían descripciones.

**Comment by dianapg8** [comment]
En el backlog se puso como "ayudar a encontrar la clave de estados y municipios" lo cual hace referencia a la función clave() que ya fue hecha, documentada y mergeada
Cree este issue para que apareciera el nombre de la función en el backlog pero lo cerre en seguida porque no recorde que se podia editar en el backlog. Oops.
